return {
	rightleftharpoons = { conceal = "⇌", desc = "Arrow: rightleftharpoons" },
	implies = { conceal = "⇒", alias = "imply", desc = "Arrow: implies" },
	mapsto = { conceal = "↦", alias = "mto", desc = "Arrow: mapsto" },
	Downarrow = { conceal = "⇓", alias = "Darr", desc = "Arrow: Downarrow" },
	nearrow = { conceal = "↗", alias = "nearr", desc = "Arrow: nearrow" },
	nwarrow = { conceal = "↖", alias = "nwarr", desc = "Arrow: nwarrow" },
	searrow = { conceal = "↘", alias = "searr", desc = "Arrow: searrow" },
	swarrow = { conceal = "↙", alias = "swarr", desc = "Arrow: swarrow" },
	Uparrow = { conceal = "⇑", alias = "Uarr", desc = "Arrow: Uparrow" },
	updownarrow = { conceal = "↕", alias = "udarr", desc = "Arrow: updownarrow" },
	Updownarrow = { conceal = "⇕", alias = "UDarr", desc = "Arrow: Updownarrow" },
	to = { conceal = "→", alias = "to", desc = "Arrow: to" },
	uparrow = { conceal = "↑", alias = "uarr", desc = "Arrow: uparrow" },
	rightarrow = { conceal = "→", alias = "rarr", desc = "Arrow: rightarrow" },
	Rightarrow = { conceal = "⇒", alias = "Rarr", desc = "Arrow: Rightarrow" },
	leftarrow = { conceal = "←", alias = "larr", desc = "Arrow: leftarrow" },
	Leftarrow = { conceal = "⇐", alias = "Larr", desc = "Arrow: Leftarrow" },
	leftharpoondown = { conceal = "↽", desc = "Arrow: leftharpoondown" },
	leftharpoonup = { conceal = "↼", desc = "Arrow: leftharpoonup" },
	leftrightarrow = { conceal = "↔", alias = "lrarr", desc = "Arrow: leftrightarrow" },
	Leftrightarrow = { conceal = "⇔", alias = "LRarr", desc = "Arrow: Leftrightarrow" },
	gets = { conceal = "←", alias = "gets", desc = "Arrow: gets" },
	iff = { conceal = "⇔", alias = "iff", desc = "Arrow: iff" },
	downarrow = { conceal = "↓", alias = "darr", desc = "Arrow: downarrow" },
	hookleftarrow = { conceal = "↩", alias = "hlarr", desc = "Arrow: hookleftarrow" },
	hookrightarrow = { conceal = "↪", alias = "hrarr", desc = "Arrow: hookrightarrow" },
}
