return {
	asymp = { conceal = "≍", alias = "asymp", desc = "Arrow: asymp" },
	approx = { conceal = "≈", alias = "apx", desc = "Arrow: approx" },
	bot = { conceal = "⊥", alias = "bot", desc = "Arrow: bot" },
	cong = { conceal = "≅", alias = "cong", desc = "Arrow: cong" },
	doteq = { conceal = "≐", alias = "doteq", desc = "Arrow: doteq" },
	equiv = { conceal = "≡", alias = "eqv", desc = "Arrow: equiv" },
	ge = { conceal = "≥", desc = "Arrow: ge" },
	geq = { conceal = "≥", alias = "geq", desc = "Arrow: geq" },
	["in"] = { conceal = "∈", alias = "in", desc = "Arrow: in" },
	le = { conceal = "≤", desc = "Arrow: le" },
	leq = { conceal = "≤", alias = "leq", desc = "Arrow: leq" },
	ll = { conceal = "≪", alias = "ll", desc = "Arrow: ll" },
	mid = { conceal = "∣", alias = "mid", desc = "Arrow: mid" },
	ne = { conceal = "≠", desc = "Arrow: ne" },
	neq = { conceal = "≠", alias = "neq", desc = "Arrow: neq" },
	ni = { conceal = "∋", alias = "ni", desc = "Arrow: ni" },
	nmid = { conceal = "∤", alias = "nmid", desc = "Arrow: nmid" },
	notin = { conceal = "∉", alias = "nin", desc = "Arrow: notin" },
	owns = { conceal = "∋", alias = "owns", desc = "Arrow: owns" },
	parallel = { conceal = "║", alias = "prll", desc = "Arrow: parallel" },
	perp = { conceal = "⊥", alias = "perp", desc = "Arrow: perp" },
	prec = { conceal = "≺", alias = "prec", desc = "Arrow: prec" },
	preceq = { conceal = "⪯", alias = "preq", desc = "Arrow: preceq" },
	propto = { conceal = "∝", alias = "prpto", desc = "Arrow: propto" },
	sim = { conceal = "∼", alias = "sim", desc = "Arrow: sim" },
	simeq = { conceal = "⋍", alias = "simeq", desc = "Arrow: simeq" },
	sqsubset = { conceal = "⊏", alias = "ssub", desc = "Arrow: sqsubset" },
	sqsubseteq = { conceal = "⊑", alias = "ssube", desc = "Arrow: sqsubseteq" },
	sqsupset = { conceal = "⊐", alias = "ssup", desc = "Arrow: sqsupset" },
	sqsupseteq = { conceal = "⊒", alias = "ssupe", desc = "Arrow: sqsupseteq" },
	subset = { conceal = "⊂", alias = "subse", desc = "Arrow: subset" },
	subseteq = { conceal = "⊆", alias = "subse", desc = "Arrow: subseteq" },
	succ = { conceal = "≻", alias = "succ", desc = "Arrow: succ" },
	succeq = { conceal = "⪰", alias = "succe", desc = "Arrow: succeq" },
	supset = { conceal = "⊃", alias = "supse", desc = "Arrow: supset" },
	supseteq = { conceal = "⊇", alias = "supse", desc = "Arrow: supseteq" },
	vdash = { conceal = "⊢", alias = "vdash", desc = "Arrow: vdash" },
}
