local M = {
	exists = { conceal = "∃", alias = "ee", desc = "Symbol: exists" },
	forall = { conceal = "∀", alias = "aa", desc = "Symbol: forall" },
	models = { conceal = "╞", alias = "mdl", desc = "Symbol: models" },
	S = { conceal = "§", alias = "S", desc = "section symbol" },
	vdots = { conceal = "⋮", alias = "vds", desc = "Symbol: vdots" },
	angle = { conceal = "∠", alias = "<", desc = "Symbol: angle" },
	cdots = { conceal = "⋯", alias = "cds", desc = "Symbol: cdots" },
	ddots = { conceal = "⋱", alias = "dds", desc = "Symbol: ddots" },
	dots = { conceal = "…", alias = "dts", desc = "Symbol: dots" },
	ldots = { conceal = "…", alias = "lds", desc = "Symbol: ldots" },
	natural = { conceal = "♮", desc = "Symbol: natural" },
	flat = { conceal = "♭", desc = "Symbol: flat" },
	sharp = { conceal = "♯", desc = "Symbol: sharp" },
	clubsuit = { conceal = "♣", desc = "Symbol: clubsuit" },
	diamondsuit = { conceal = "♢", desc = "Symbol: diamondsuit" },
	heartsuit = { conceal = "♡", desc = "Symbol: heartsuit" },
	spadesuit = { conceal = "♠", desc = "Symbol: spadesuit" },
	imath = { conceal = "ɩ", desc = "Symbol: imath" },
	jmath = { conceal = "𝚥", desc = "Symbol: jmath" },
	emptyset = { conceal = "∅", alias = "oset", desc = "Symbol: emptyset" },
	varnothing = { conceal = "∅", desc = "Symbol: varnothing" },
	hbar = { conceal = "ℏ", alias = "hbar", desc = "Symbol: hbar" },
	ell = { conceal = "ℓ", alias = "ell", desc = "Symbol: ell" },
	infty = { conceal = "∞", alias = "ifn", desc = "Symbol: infty" },
	aleph = { conceal = "ℵ", alias = "ale", desc = "Symbol: aleph" },
	wp = { conceal = "℘", alias = "wp", desc = "Symbol: wp" },
	wr = { conceal = "≀", alias = "wr", desc = "Symbol: wr" },
	["\\"] = { conceal = "", desc = "Symbol: \\" },
}
return M
