local M = {}
M.overline = function(char)
	return char .. "̅"
end
M.bar = M.overline
M.subscript = {
	[")"] = "₎",
	["("] = "₍",
	["="] = "₌",
	[" "] = "",
	["0"] = "₀",
	["1"] = "₁",
	["2"] = "₂",
	["3"] = "₃",
	["4"] = "₄",
	["5"] = "₅",
	["6"] = "₆",
	["7"] = "₇",
	["8"] = "₈",
	["9"] = "₉",
	["a"] = "ₐ",
	["c"] = "꜀",
	["e"] = "ₑ",
	["h"] = "ₕ",
	["i"] = "ᵢ",
	["j"] = "ⱼ",
	["k"] = "ₖ",
	["l"] = "ₗ",
	["m"] = "ₘ",
	["n"] = "ₙ",
	["o"] = "ₒ",
	["p"] = "ₚ",
	["r"] = "ᵣ",
	["s"] = "ₛ",
	["t"] = "ₜ",
	["u"] = "ᵤ",
	["v"] = "ᵥ",
	["x"] = "ₓ",
	["."] = "‸",
	["+"] = "₊",
	["-"] = "₋",
	["/"] = "ˏ",
	[","] = ",",
}
M.superscript = {
	["∞"] = " ᪲",
	[","] = "˒",
	["0"] = "⁰",
	["1"] = "¹",
	["2"] = "²",
	["3"] = "³",
	["4"] = "⁴",
	["5"] = "⁵",
	["6"] = "⁶",
	["7"] = "⁷",
	["8"] = "⁸",
	["9"] = "⁹",
	["a"] = "ᵃ",
	["b"] = "ᵇ",
	["c"] = "ᶜ",
	["d"] = "ᵈ",
	["e"] = "ᵉ",
	["f"] = "ᶠ",
	["g"] = "ᵍ",
	["h"] = "ʰ",
	["i"] = "ⁱ",
	["j"] = "ʲ",
	["k"] = "ᵏ",
	["l"] = "ˡ",
	["m"] = "ᵐ",
	["n"] = "ⁿ",
	["o"] = "ᵒ",
	["p"] = "ᵖ",
	["r"] = "ʳ",
	["s"] = "ˢ",
	["t"] = "ᵗ",
	["u"] = "ᵘ",
	["v"] = "ᵛ",
	["w"] = "ʷ",
	["x"] = "ˣ",
	["y"] = "ʸ",
	["z"] = "ᶻ",
	["A"] = "ᴬ",
	["B"] = "ᴮ",
	["D"] = "ᴰ",
	["E"] = "ᴱ",
	["G"] = "ᴳ",
	["H"] = "ᴴ",
	["I"] = "ᴵ",
	["J"] = "ᴶ",
	["K"] = "ᴷ",
	["L"] = "ᴸ",
	["M"] = "ᴹ",
	["N"] = "ᴺ",
	["O"] = "ᴼ",
	["P"] = "ᴾ",
	["R"] = "ᴿ",
	["T"] = "ᵀ",
	["U"] = "ᵁ",
	["V"] = "ⱽ",
	["W"] = "ᵂ",
	["+"] = "⁺",
	["-"] = "⁻",
	["<"] = "˂",
	[">"] = "˃",
	-- ["/"] = "ˊ",
	["."] = "˙",
	["="] = "⁼",
	["*"] = "*",
	[" "] = "",
	["("] = "⁽",
	[")"] = "⁾",
}
M.mathsf = {
	["a"] = "𝖺",
	["b"] = "𝖻",
	["c"] = "𝖼",
	["d"] = "𝖽",
	["e"] = "𝖾",
	["f"] = "𝖿",
	["g"] = "𝗀",
	["h"] = "𝗁",
	["i"] = "𝗂",
	["j"] = "𝗃",
	["k"] = "𝗄",
	["l"] = "𝗅",
	["m"] = "𝗆",
	["n"] = "𝗇",
	["o"] = "𝗈",
	["p"] = "𝗉",
	["q"] = "𝗊",
	["r"] = "𝗋",
	["s"] = "𝗌",
	["t"] = "𝗍",
	["u"] = "𝗎",
	["v"] = "𝗏",
	["w"] = "𝗐",
	["x"] = "𝗑",
	["y"] = "𝗒",
	["z"] = "𝗓",
	["A"] = "𝖠",
	["B"] = "𝖡",
	["C"] = "𝖢",
	["D"] = "𝖣",
	["E"] = "𝖤",
	["F"] = "𝖥",
	["G"] = "𝖦",
	["H"] = "𝖧",
	["I"] = "𝖨",
	["J"] = "𝖩",
	["K"] = "𝖪",
	["L"] = "𝖫",
	["M"] = "𝖬",
	["N"] = "𝖭",
	["O"] = "𝖮",
	["P"] = "𝖯",
	["Q"] = "𝖰",
	["R"] = "𝖱",
	["S"] = "𝖲",
	["T"] = "𝖳",
	["U"] = "𝖴",
	["V"] = "𝖵",
	["W"] = "𝖶",
	["X"] = "𝖷",
	["Y"] = "𝖸",
	["Z"] = "𝖹",
}
M.mathfrak = {
	["a"] = "𝔞",
	["b"] = "𝔟",
	["c"] = "𝔠",
	["d"] = "𝔡",
	["e"] = "𝔢",
	["f"] = "𝔣",
	["g"] = "𝔤",
	["h"] = "𝔥",
	["i"] = "𝔦",
	["j"] = "𝔧",
	["k"] = "𝔨",
	["l"] = "𝔩",
	["m"] = "𝔪",
	["n"] = "𝔫",
	["o"] = "𝔬",
	["p"] = "𝔭",
	["q"] = "𝔮",
	["r"] = "𝔯",
	["s"] = "𝔰",
	["t"] = "𝔱",
	["u"] = "𝔲",
	["v"] = "𝔳",
	["w"] = "𝔴",
	["x"] = "𝔵",
	["y"] = "𝔶",
	["z"] = "𝔷",
	["A"] = "𝔄",
	["B"] = "𝔅",
	["C"] = "ℭ",
	["D"] = "𝔇",
	["E"] = "𝔈",
	["F"] = "𝔉",
	["G"] = "𝔊",
	["H"] = "ℌ",
	["I"] = "ℑ",
	["J"] = "𝔍",
	["K"] = "𝔎",
	["L"] = "𝔏",
	["M"] = "𝔐",
	["N"] = "𝔑",
	["O"] = "𝔒",
	["P"] = "𝔓",
	["Q"] = "𝔔",
	["R"] = "ℜ",
	["S"] = "𝔖",
	["T"] = "𝔗",
	["U"] = "𝔘",
	["V"] = "𝔙",
	["W"] = "𝔚",
	["X"] = "𝔛",
	["Y"] = "𝔜",
	["Z"] = "ℨ",
}
M.mathscr = {
	A = "𝒜",
	B = "ℬ",
	C = "𝒞",
	D = "𝒟",
	E = "ℰ",
	F = "ℱ",
	G = "𝒢",
	H = "ℋ",
	I = "ℐ",
	J = "𝒥",
	K = "𝒦",
	L = "ℒ",
	M = "ℳ",
	N = "𝒩",
	O = "𝒪",
	P = "𝒫",
	Q = "𝒬",
	R = "ℛ",
	S = "𝒮",
	T = "𝒯",
	U = "𝒰",
	V = "𝒱",
	W = "𝒲",
	X = "𝒳",
	Y = "𝒴",
	Z = "𝒵",
}
M.mathcal = M.mathscr
M.mathbbm = {
	a = "𝕒",
	b = "𝕓",
	c = "𝕔",
	d = "𝕕",
	e = "𝕖",
	f = "𝕗",
	g = "𝕘",
	h = "𝕙",
	i = "𝕚",
	j = "𝕛",
	k = "𝕜",
	l = "𝕝",
	m = "𝕞",
	n = "𝕟",
	o = "𝕠",
	p = "𝕡",
	q = "𝕢",
	r = "𝕣",
	s = "𝕤",
	t = "𝕥",
	u = "𝕦",
	v = "𝕧",
	w = "𝕨",
	x = "𝕩",
	y = "𝕪",
	z = "𝕫",
	["0"] = "𝟘",
	["1"] = "𝟙",
	["2"] = "𝟚",
	["3"] = "𝟛",
	["4"] = "𝟜",
	["5"] = "𝟝",
	["6"] = "𝟞",
	["7"] = "𝟟",
	["8"] = "𝟠",
	["9"] = "𝟡",
	["A"] = "𝔸",
	["B"] = "𝔹",
	["C"] = "ℂ",
	["D"] = "𝔻",
	["E"] = "𝔼",
	["F"] = "𝔽",
	["G"] = "𝔾",
	["H"] = "ℍ",
	["I"] = "𝕀",
	["J"] = "𝕁",
	["K"] = "𝕂",
	["L"] = "𝕃",
	["M"] = "𝕄",
	["N"] = "ℕ",
	["O"] = "𝕆",
	["P"] = "ℙ",
	["Q"] = "ℚ",
	["R"] = "ℝ",
	["S"] = "𝕊",
	["T"] = "𝕋",
	["U"] = "𝕌",
	["V"] = "𝕍",
	["W"] = "𝕎",
	["X"] = "𝕏",
	["Y"] = "𝕐",
	["Z"] = "ℤ",
}
M.mathbb = M.mathbbm
local function swapcase(s)
	return (s:gsub("%a", function(c)
		if c:match("%l") then
			return c:upper()
		else
			return c:lower()
		end
	end))
end
M.items = {
	["mathfk"] = {
		narg = 1,
		oarg = false,
		class = "function",
		tex = "\\mathfrak",
		alias = "fk",
		onechar_expand = {
			conceal = function(char)
				return M.mathfrak[swapcase(char)]
			end,
			class = "symbol",
			tex = function(char)
				return [[\mathfrak{]] .. swapcase(char) .. "}"
			end,
			alias = "fk(%a)",
		},
	},
	["mathbb"] = {
		narg = 1,
		oarg = false,
		class = "function",
		tex = "\\mathbb",
		alias = "bb",
		onechar_expand = {

			conceal = function(char)
				return M.mathbb[swapcase(char)]
			end,
			class = "symbol",
			tex = function(char)
				return [[\mathbb{]] .. swapcase(char) .. "}"
			end,
			alias = "bb(%a)",
		},
	},
	["mathbbm"] = {
		narg = 1,
		oarg = false,
		class = "function",
		tex = "\\mathbbm",
		alias = "bm",
		onechar_expand = {

			conceal = function(char)
				return M.mathbbm[swapcase(char)]
			end,
			class = "symbol",
			tex = function(char)
				return [[\mathbbm{]] .. swapcase(char) .. "}"
			end,
			alias = "bm(%a)",
		},
	},
	["mathcal"] = {
		narg = 1,
		oarg = false,
		class = "function",
		tex = "\\mathcal",
		alias = "cal",
		onechar_expand = {

			conceal = function(char)
				return M.mathcal[string.upper(char)]
			end,
			class = "symbol",
			tex = function(char)
				return [[\mathcal{]] .. string.upper(char) .. "}"
			end,
			alias = "cal(%a)",
		},
	},
	["mathscr"] = {
		narg = 1,
		oarg = false,
		class = "function",
		tex = "\\mathscr",
		alias = "scr",
		onechar_expand = {

			conceal = function(char)
				return M.mathscr[string.upper(char)]
			end,
			class = "symbol",
			tex = function(char)
				return [[\mathscr{]] .. string.upper(char) .. "}"
			end,
			alias = "scr(%a)",
		},
	},
	["mathbf"] = {
		narg = 1,
		oarg = false,
		class = "function",
		tex = "\\mathbf",
		alias = "bf",
		onechar_expand = {

			conceal = function(char)
				return char
			end,
			class = "symbol",
			tex = "\\mathbf{%1}",
			alias = "bf(%a)",
		},
	},
	["mathrm"] = {
		narg = 1,
		oarg = false,
		class = "function",
		tex = "\\mathrm",
		alias = "rm",
		onechar_expand = {

			conceal = function(char)
				return char
			end,
			class = "constant",
			tex = "\\mathrm{%1}",
			alias = "rm(%a)",
		},
	},
	["overline"] = {
		narg = 1,
		oarg = false,
		class = "function",
		tex = "\\overline",
		alias = "bar",
		onechar_expand = {
			conceal = function(char)
				return char .. "̅"
			end,
			class = "math",
			tex = "\\overline{%1}",
			alias = "(%a)bar",
		},
	},
	["text"] = {
		narg = 1,
		oarg = false,
		class = "function",
		tex = "\\text",
		alias = "te",
		onechar_expand = {
			conceal = function(char)
				return char
			end,
			class = "constant",
			tex = "\\text{%1}",
			alias = "te(%a)",
		},
	},
}
return M
